export const INDUSTRIES = [
  'Accounting & Finance',
  'Administrative & Office Support',
  'Advertising & Marketing',
  'Aerospace & Aviation',
  'Agriculture & Farming',
  'Architecture & Design',
  'Arts, Entertainment & Media',
  'Automotive',
  'Banking & Financial Services',
  'Biotechnology',
  'Business Services',
  'Call Center & Customer Service',
  'Childcare & Early Education',
  'Construction',
  'Consulting',
  'Consumer Goods',
  'Education',
  'Energy & Utilities',
  'Engineering',
  'Environmental Services',
  'Event Planning & Hospitality',
  'Fashion & Apparel',
  'Food & Beverage',
  'Government & Public Administration',
  'Graphic Design & Creative Services',
  'Healthcare',
  'Home Services',
  'Human Resources',
  'Import & Export',
  'Information Technology (IT)',
  'Insurance',
  'Legal Services',
  'Logistics, Transportation & Supply Chain',
  'Manufacturing',
  'Nonprofit & Social Services',
  'Pharmaceuticals',
  'Printing & Publishing',
  'Real Estate',
  'Recruitment & Staffing',
  'Research & Development',
  'Retail',
  'Sales',
  'Security & Investigations',
  'Skilled Trades',
  'Software & Technology',
  'Sports & Recreation',
  'Telecommunications',
  'Tourism & Travel',
  'Warehousing & Distribution',
  'Wholesale',
  'Other',
];
